/**
 * Program Membership Data Types & Content Definitions
 * Based on Joyzen Membership Section Content specifications.
 */

export interface MembershipPlanTier {
  /** Unique tier identifier */
  id: string;
  /** Label for the duration selector tab (e.g. 'Monthly', '3 Months', '6 Months') */
  durationTitle: string;
  /** Subtitle for the duration selector tab (e.g. 'Flexible', 'Save ₹357', 'Save ₹1,074') */
  durationSubtitle: string;
  /** Highlight badge on the plan card (e.g. 'Biggest Savings', 'Most Chosen', 'Flexible') */
  badge: string;
  /** Optional emoji/icon for the badge */
  badgeEmoji?: string;
  /** Original daily price displayed with strikethrough (e.g. '₹50') */
  originalDailyPrice?: string;
  /** Current effective daily price (e.g. '₹44') */
  dailyPrice: string;
  /** Price unit label (default: '/Day') */
  priceUnit?: string;
  /** Savings pill text (e.g. 'Save ₹1,074') */
  savingsBadge?: string;
  /** Comparison text next to savings pill (e.g. 'vs paying monthly') */
  savingsComparisonText?: string;
  /** Summary of plan commitment (e.g. '6 Month Care Plan · ₹7,920 for 6 months') */
  planSummary: string;
  /** Call to action button label (e.g. 'CHOOSE 6 MONTHS') */
  ctaButtonText: string;
}

export interface MembershipCareTeamBlock {
  text: string;
  buttonText: string;
}

export interface MembershipProgramData {
  /** Program identifier key */
  programKey: 'luna' | 'lyra' | 'cala' | 'eve' | 'core' | 'atlas' | 'genesis' | 'vita' | 'eve-genesis';
  /** Program display name */
  programName: string;
  /** Accent color for the program name in titles */
  programHighlightColor: string;
  /** Section hero tagline */
  tagline: string;
  /** Section description / subtitle */
  subtitle: string;
  /** Default selected plan tier id (usually '6-months') */
  defaultPlanId?: string;
  /** Available plan tiers (Monthly, 3 Months, 6 Months) */
  plans: MembershipPlanTier[];
  /** Title for the checklist card (e.g. 'Every LUNA membership includes') */
  includedTitle: string;
  /** Feature list for the checklist card */
  includedFeatures: string[];
  /** Supporting line beneath cards */
  supportingLine: string;
  /** Care team guidance block */
  careTeamBlock: MembershipCareTeamBlock;
  /** Post-enrollment timeline notice */
  afterEnrollmentNotice: string;
  /** Concluding statement */
  closingStatement: string;
}

export type ProgramKey = MembershipProgramData['programKey'];

export const PROGRAM_MEMBERSHIP_DATA: Record<ProgramKey, MembershipProgramData> = {
  luna: {
    programKey: 'luna',
    programName: 'LUNA',
    programHighlightColor: '#958CD5',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: 'Most members start with a 3-month program for best results, but you can start monthly.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹50',
        priceUnit: '/Day',
        planSummary: 'Monthly Care Plan · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹357',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹50',
        dailyPrice: '₹46',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹357',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Care Plan · ₹4,140 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹1,074',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹50',
        dailyPrice: '₹44',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹1,074',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Care Plan · ₹7,920 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every LUNA membership \nincludes',
    includedFeatures: [
      '3 doctor consultations every month',
      'Cycle education',
      'Personalized diet plan',
      'Monthly / weekly progress review',
      'Lifestyle coaching',
      'Daily care team support',
      'Tracking guidance',
      'Fitness / yoga plan',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'After enrollment, our care team will contact you within 24 hours to begin your LUNA program.',
    closingStatement: 'Most LUNA members continue for 3–6 months to see meaningful improvement and confidence in their health.',
  },

  lyra: {
    programKey: 'lyra',
    programName: 'LYRA',
    programHighlightColor: '#CB6D7A',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: "For women who want to improve their health, hormones, cycle, and overall wellbeing with continuous medical and lifestyle guidance.",
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹77',
        priceUnit: '/Day',
        planSummary: 'Monthly Care Plan · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹597',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹77',
        dailyPrice: '₹70',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹597',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Care Plan · ₹6,300 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹1,914',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹77',
        dailyPrice: '₹66',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹1,914',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Care Plan · ₹11,880 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every LYRA membership \nincludes',
    includedFeatures: [
      '3 monthly 1-to-1 consultations',
      'Personalized cycle + hormone optimization plan',
      'Intimate health check-ins',
      'Vaginal & uterine wellness guidance',
      'Symptom + red-flag monitoring',
      'Supplement + lifestyle protocol',
      'Cycle & ovulation insight report',
      'Fertility readiness score',
      'Private women’s health chat support',
      'Dedicated care buddy',
      'Progress + emotional wellbeing tracking',
      'Personalized diet plan',
      'Home or gym workout plan',
      'Monthly plan adjustments',
      'Lifestyle habit coaching',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'All memberships include full LYRA support, consultations, and lifestyle planning.',
    closingStatement: 'Most LYRA members stay for at least 3 months to see meaningful improvement in cycle, energy, and overall health.',
  },

  cala: {
    programKey: 'cala',
    programName: 'CALA',
    programHighlightColor: '#008080',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: 'Most members start with a 3-month program for best results, but you can start monthly.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹177',
        priceUnit: '/Day',
        planSummary: 'Monthly Care Plan · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹960',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹177',
        dailyPrice: '₹166',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹960',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Care Plan · ₹14,940 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹2,820',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹177',
        dailyPrice: '₹161',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹2,820',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Care Plan · ₹28,980 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every CALA membership \nincludes',
    includedFeatures: [
      'Same gynecologist for long-term care',
      'Monthly detailed consultations',
      'Weekly care team check-ins',
      'Daily private chat support',
      'Hormone tracking dashboard',
      'Cycle rebuilding program',
      'Ovulation tracking',
      'PCOS improvement tracking',
      'Fertility readiness tracking',
      'Vaginal & uterine health guidance',
      'Period pain & PMS plan',
      'Infection prevention guidance',
      'Pelvic health awareness',
      'Dedicated care companion',
      'Stress & emotional wellbeing tracking',
      'Monthly emotional health review',
      'Personalized diet plan',
      'Home / gym workout plan',
      'Monthly plan adjustments',
      'Lifestyle habit coaching',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'CALA is a structured healing program. Most members stay for 3–6 months for proper hormone and cycle recovery.',
    closingStatement: 'CALA is for women who are serious about fixing their hormones and cycle, not just managing symptoms.',
  },

  eve: {
    programKey: 'eve',
    programName: 'EVE',
    programHighlightColor: '#DD9057',
    tagline: 'Pregnancy, Prepared With a Plan.',
    subtitle: 'For women who want to prepare their body and conceive naturally with step-by-step medical guidance.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹267',
        priceUnit: '/Day',
        planSummary: 'Monthly Care Plan · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹2,037',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹267',
        dailyPrice: '₹244',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹2,037',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Preparation Program · ₹21,960 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹8,034',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹267',
        dailyPrice: '₹222',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹8,034',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Preparation Program · ₹39,960 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every EVE membership \nincludes',
    includedFeatures: [
      'Dedicated gynecologist for full journey',
      'Monthly deep fertility consultations',
      'Weekly follow-ups & ovulation guidance',
      'Daily private chat support',
      'Ovulation & fertile window tracking',
      'Cycle quality analysis',
      'Hormone optimization plan',
      'Egg health support',
      'Uterine lining support',
      'Conception timing plan',
      'Step-by-step conception roadmap',
      'Partner fertility guidance',
      'Male fertility awareness',
      'Conception timing coordination',
      'Emotional support for both partners',
      'Personalized diet plan',
      'Home / gym workout plan',
      'Monthly plan adjustments',
      'Lifestyle habit coaching',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'Preparing for pregnancy costs less than one IVF injection.',
    closingStatement: 'Most EVE members continue for 3–6 months for comprehensive conception readiness.',
  },

  core: {
    programKey: 'core',
    programName: 'CORE',
    programHighlightColor: '#6BACE5',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: 'For men who want to improve energy, lifestyle, sexual health, and prevent future fertility problems with guided medical support.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹50',
        priceUnit: '/Day',
        planSummary: 'Monthly CORE Program · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹537',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹50',
        dailyPrice: '₹44',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹537',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month CORE Program · ₹3,960 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹1,614',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹50',
        dailyPrice: '₹41',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹1,614',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month CORE Program · ₹7,380 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every CORE membership \nincludes',
    includedFeatures: [
      '3 one-to-one doctor consultations per month',
      'Daily private men’s health chat',
      'Symptom review & personalized guidance',
      'Basic hormone guidance',
      'Libido & erection guidance',
      'Lab report explanation',
      'Red-flag detection & referral',
      'Sleep, stress & recovery guidance',
      'Emotional & confidence support',
      'Monthly health progress check-ins',
      'Reproductive infection prevention education',
      'Testicular self-exam awareness',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'After enrollment, our care team will contact you within 24 hours to begin your CORE program.',
    closingStatement: 'Most CORE members stay for at least 3 months to see improvements in energy, stress, and overall health.',
  },

  atlas: {
    programKey: 'atlas',
    programName: 'ATLAS',
    programHighlightColor: '#5A856C',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: 'For men who want to improve sperm health, testosterone, stamina, and reproductive health with structured medical and lifestyle guidance.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹183',
        priceUnit: '/Day',
        planSummary: 'Monthly Recovery Program · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Most Chosen',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹183',
        dailyPrice: '₹166',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹1,530',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Recovery Program · ₹14,940 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹5,100',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹183',
        dailyPrice: '₹155',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹5,100',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Recovery Program · ₹27,900 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every ATLAS membership \nincludes',
    includedFeatures: [
      'Dedicated Andrologist / Men’s Health Doctor',
      '3 personal consultations per month',
      'Semen analysis & lab report interpretation',
      'Monthly fertility & hormone review',
      'Male fertility score & progress tracking',
      'Hormone tracking dashboard',
      'Libido & erection quality monitoring',
      'Ejaculation comfort guidance',
      'Testicular health monitoring',
      'Fertility readiness index',
      'Personalized supplement protocol',
      'Sleep, stress & lifestyle correction plan',
      'Daily private fertility support chat',
      'Priority Q&A support',
      'Red-flag detection & early intervention guidance',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'After enrollment, our care team will contact you within 24 hours to begin your ATLAS program.',
    closingStatement: 'Most ATLAS members continue for 3–6 months for complete sperm cycle renewal and hormone recovery.',
  },

  genesis: {
    programKey: 'genesis',
    programName: 'GENESIS',
    programHighlightColor: '#7D7CCD',
    tagline: 'Start small. Continue with guidance. Build health early.',
    subtitle: 'For men preparing for fatherhood, with guided fertility, hormone, sexual health and lifestyle support.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹266',
        priceUnit: '/Day',
        planSummary: 'Monthly Genesis Program · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Save ₹1,980',
        badge: 'Most Chosen',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹266',
        dailyPrice: '₹244',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹1,980',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Genesis Program · ₹21,960 for 3 months',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹9,000',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹266',
        dailyPrice: '₹216',
        priceUnit: '/Day',
        savingsBadge: 'Save ₹9,000',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Genesis Program · ₹38,880 for 6 months',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every GENESIS membership \nincludes',
    includedFeatures: [
      'Dedicated andrologist for entire journey',
      'Monthly deep fertility consultations',
      'Weekly follow-ups & progress check-ins',
      'Daily private men’s health chat',
      'Sperm health tracking',
      'Hormone optimization plan',
      'Fertility readiness index',
      'Semen quality improvement strategy',
      'Conception timing guidance',
      'Step-by-step fertility improvement roadmap',
      'Libido & performance support',
      'Erectile health guidance',
      'Ejaculation quality monitoring',
      'Infection prevention guidance',
      'Testicular health awareness',
      'Intimacy confidence support',
      'Personalized diet plan',
      'Home / gym workout plan',
      'Monthly plan adjustments',
      'Lifestyle habit coaching',
      'Dedicated care companion',
      'Monthly emotional wellbeing review',
      'Stress & anxiety support',
      'Confidence & performance support',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'After enrollment, our care team will contact you within 24 hours to begin your GENESIS program.',
    closingStatement: 'GENESIS prepares men for fatherhood before conception begins.',
  },

  vita: {
    programKey: 'vita',
    programName: 'VITA',
    programHighlightColor: '#DB623F',
    tagline: 'Natural Conception Program',
    subtitle: 'Joyzen Clinic’s fertility program for couples trying to conceive, with complete fertility evaluation, personalized conception planning and continuous medical support.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹332',
        priceUnit: '/couple',
        planSummary: 'Monthly Program · Flexible billing for couple',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Most Couples Choose',
        badge: 'Most Couples Choose This',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹166',
        dailyPrice: '₹155',
        priceUnit: '/person/day',
        savingsBadge: 'Save ₹1,980',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Program · ₹27,900 for both',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹7,794',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹166',
        dailyPrice: '₹145',
        priceUnit: '/person/day',
        savingsBadge: 'Save ₹7,794',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Program · ₹52,200 for both',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every VITA membership \nincludes',
    includedFeatures: [
      'Male + female fertility assessment',
      'Hormone & cycle assessment',
      'Semen analysis review',
      'Uterine readiness monitoring',
      'Lab report interpretation',
      'Ovulation & fertile window tracking',
      'Conception timing guidance',
      'Cycle quality analysis',
      'Sperm health improvement plan',
      'Step-by-step conception roadmap',
      'Personalized medication support, if required',
      'Dedicated gynecologist + andrologist',
      'Weekly medical follow-ups',
      'Daily care team chat support',
      'Red-flag detection & early intervention guidance',
      'Fertility diet plan',
      'Ovulation-support workouts / yoga',
      'Hormone balance lifestyle plan',
      'Sleep & stress routine',
      'Sperm health diet plan',
      'Testosterone-support workouts',
      'Stamina & recovery plan',
      'Lifestyle correction plan',
      'Couple lifestyle plan',
      'Stress reduction routine',
      'Habit coaching',
      'Monthly plan adjustments',
      'Emotional reassurance during trying period',
      'Stress & anxiety support',
      'Guidance during two-week wait',
      'Continuous support so couples don’t feel lost',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'After enrollment, our care team will contact you within 24 hours to begin your VITA program.',
    closingStatement: 'Most couples choose 3–6 months for lasting fertility results.',
  },

  'eve-genesis': {
    programKey: 'eve-genesis',
    programName: 'EVE + GENESIS',
    programHighlightColor: '#8F9B6F',
    tagline: 'Couple Conception Program',
    subtitle: 'For couples who want to prepare and conceive naturally with guided support for both partners.',
    defaultPlanId: '6-months',
    plans: [
      {
        id: 'monthly',
        durationTitle: 'Monthly',
        durationSubtitle: 'Flexible',
        badge: 'Flexible',
        dailyPrice: '₹166',
        priceUnit: '/person/day',
        planSummary: 'Monthly Couple Program · Flexible billing',
        ctaButtonText: 'START MONTHLY',
      },
      {
        id: '3-months',
        durationTitle: '3 Months',
        durationSubtitle: 'Popular',
        badge: 'Popular',
        badgeEmoji: '⭐',
        originalDailyPrice: '₹166',
        dailyPrice: '₹150',
        priceUnit: '/person/day',
        savingsBadge: 'Save ₹2,880',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '3 Month Couple Program · ₹27,000 for both',
        ctaButtonText: 'CHOOSE 3 MONTHS',
      },
      {
        id: '6-months',
        durationTitle: '6 Months',
        durationSubtitle: 'Save ₹5,040',
        badge: 'Biggest Savings',
        badgeEmoji: '💰',
        originalDailyPrice: '₹166',
        dailyPrice: '₹138',
        priceUnit: '/person/day',
        savingsBadge: 'Save ₹5,040',
        savingsComparisonText: 'vs paying monthly',
        planSummary: '6 Month Couple Program · ₹49,680 for both',
        ctaButtonText: 'CHOOSE 6 MONTHS',
      },
    ],
    includedTitle: 'Every EVE + GENESIS membership \nincludes',
    includedFeatures: [
      'FOR HER — Ovulation tracking',
      'FOR HER — Hormone optimization',
      'FOR HER — Egg & uterine health support',
      'FOR HER — Gynecologist consultations',
      'FOR HER — Diet & fitness plan',
      'FOR HIM — Sperm health improvement',
      'FOR HIM — Testosterone & hormone support',
      'FOR HIM — Lifestyle & stamina improvement',
      'FOR HIM — Semen report guidance',
      'FOR HIM — Diet & workout plan',
      'FOR BOTH — Conception timing plan',
      'FOR BOTH — Monthly couple consultation',
      'FOR BOTH — Weekly follow-ups',
      'FOR BOTH — Daily chat support',
      'FOR BOTH — Emotional support',
      'FOR BOTH — Step-by-step conception roadmap',
      'Scientifically designed Joyzen formulations',
    ],
    supportingLine: 'The longer you stay, the less you pay per day and the better your results.',
    careTeamBlock: {
      text: 'You can start your program directly, or speak with our care team first so we can understand you better and guide you properly.',
      buttonText: 'TALK TO CARE TEAM',
    },
    afterEnrollmentNotice: 'Most couples stay in the program for 3–6 months for proper preparation and conception guidance.',
    closingStatement: 'You are not just trying for a baby. You are preparing two bodies to create one life.',
  },
};
